language: python
python:
  - '2.7'
env:
  - DJANGO=1.4.3
  - DJANGO=1.9.12
  - DJANGO=1.10.6
install:
  - pip install -q Django==$DJANGO
  - pip install .
  - pip install -r requirements_test.txt
script: coverage run run_tests.py
after_success: coveralls
notifications:
  hipchat: 5534a6204d6caa1a45ac2444282aca@WebDevActivity
  email: false
